name: Build Darwin ARM64
on:
  workflow_call:
    inputs:
      arch:
        required: true
        type: string
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'
      - name: Set environment variables
        run: |
          MINIMOVE_NETWORK_NAME="minimove-1"
          echo "MINIMOVE_NETWORK_NAME=${MINIMOVE_NETWORK_NAME}" >> $GITHUB_ENV
          # Read MOVEVM_VERSION from config file
          MOVEVM_VERSION=$(go list -m github.com/initia-labs/movevm | awk '{print $2}')    
          echo "MOVEVM_VERSION=${MOVEVM_VERSION}" >> $GITHUB_ENV        
          echo "GOARCH=${{ inputs.arch }}" >> $GITHUB_ENV
          echo "GOOS=darwin" >> $GITHUB_ENV
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION="v0.0.0-${GITHUB_SHA::8}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          if [ "${{ inputs.arch }}" == "amd64" ]; then
            echo "ARCH_NAME=x86_64" >> $GITHUB_ENV
          elif [ "${{ inputs.arch }}" == "arm64" ]; then
            echo "ARCH_NAME=aarch64" >> $GITHUB_ENV
          else
            echo "ARCH_NAME=${{ inputs.arch }}" >> $GITHUB_ENV
          fi
          
      - name: Ensure dependencies
        run: |
          go mod tidy
          go get github.com/initia-labs/movevm@${MOVEVM_VERSION}
          
      - name: Print environment variables
        run: |
          echo "GOARCH=${GOARCH}"
          echo "GOOS=${GOOS}"
          echo "VERSION=${VERSION}"
          echo "ARCH_NAME=${ARCH_NAME}"
          echo "MINIMOVE_NETWORK_NAME=${MINIMOVE_NETWORK_NAME}"
      
      - name: Build and Package for Darwin ARM64
        run: |
          cd ../minimove \
          && make build \
          && cd ./build \
          && cp ~/go/pkg/mod/github.com/initia-labs/movevm@${MOVEVM_VERSION}/api/libmovevm.dylib ./ \
          && cp ~/go/pkg/mod/github.com/initia-labs/movevm@${MOVEVM_VERSION}/api/libcompiler.dylib ./ \
          && tar -czvf minimove_"$VERSION"_Darwin_"$ARCH_NAME".tar.gz minitiad libmovevm.dylib libcompiler.dylib \
          && mv ./minimove_"$VERSION"_Darwin_"$ARCH_NAME".tar.gz $GITHUB_WORKSPACE/ \
          && rm -rf ./libmovevm.dylib ./libcompiler.dylib ./minitiad
  
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            minimove_${{ env.VERSION }}_Darwin_${{ env.ARCH_NAME }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
