name: Build and Upload to releases

on:
  push:
    tags:
      - 'v*'

jobs:
  # build-linux-amd64:
  #   uses: ./.github/workflows/build-linux-amd64.yml
  #   with:
  #     arch: amd64
  #   secrets: inherit

  # build-linux-arm64:
  #   uses: ./.github/workflows/build-linux-arm64.yml
  #   with:
  #     arch: arm64
  #   secrets: inherit

  build-darwin-amd64:
    uses: ./.github/workflows/build-darwin-amd64.yml
    with:
      arch: amd64
    secrets: inherit

  build-darwin-arm64:
    uses: ./.github/workflows/build-darwin-arm64.yml
    with:
      arch: arm64
    secrets: inherit    
